### ISSUE TITLE
DB接続タイムアウト

### ISSUE THREAD

**Issue by ktakada42** [ktakada42/ChatGPT_LINE_Bot#3]
```
Error: target: messages_history.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1679189539323256556: ended at 2023-03-20 08:43:43.742 UTC (exceeded timeout: 20s) (CallerID: 4ziy323w4zmt2a9w1j8u)
at PromiseConnection.rollback (/opt/render/project/src/node_modules/mysql2/promise.js:153:22)
at /opt/render/project/src/server.js:111:49
at step (/opt/render/project/src/server.js:33:23)
at Object.throw (/opt/render/project/src/server.js:14:53)
at rejected (/opt/render/project/src/server.js:6:65)
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
code: 'ER_UNKNOWN_ERROR',
errno: 1105,
sql: 'ROLLBACK',
sqlState: 'HY000',
sqlMessage: 'target: messages_history.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1679189539323256556: ended at 2023-03-20 08:43:43.742 UTC (exceeded timeout: 20s) (CallerID: 4ziy323w4zmt2a9w1j8u)'
Mar 20 05:48:35 PM  }
```

**Comment by ktakada42** [comment]
#4
